include: package:mpf_analysis_options/analysis_options.yaml
analyzer:
  errors:
    # Needed for freezed with json_serializable: https://github.com/rrousselGit/freezed/issues/488
    invalid_annotation_target: ignore
  exclude:
    # This is for anyone using fvm
    - 'default/*'