name: fluttermodule
description: Fall prevention exercise app
version: 3.0.11+1
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.22.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: 4.11.0


dev_dependencies:
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  module:
    ios: true
    androidX: true
    androidPackage: au.org.standingtall
    iosBundleIdentifier: au.org.standingtall
# sentry:
#   project: fluttermodule
#   org: miroma-project-factory
#   ignore_missing: true

flutter_gen:
  output: lib/assets_gen/
  line_length: 1000
  integrations:
    flutter_svg: false
    rive: false
    lottie: false
